from tkinter import *
from PIL import ImageTk, Image
import webbrowser as wb
import random
from tkinter import messagebox

def mood_tracker():
                   root1 = Toplevel()
                   topFrame = Frame(root1)
                   topFrame.pack(side= TOP)
                   bottomFrame = Frame(root1)
                   bottomFrame.pack(side=BOTTOM)
                   root1.title('Mood Tracker')
                   #set window color
                   root1.configure(bg='pink')
                   root1.geometry("1800x1800")
                  
                   #MOOD TIPS FUNCTION
                   def mood_tip_suggest1(button):
                       if  button == ("button1"):
                            root1= Toplevel()
                            root1.geometry("1600x1600")
                            root1.title("Mood care tips")
                            l1= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                            l1.place(x=300,y=100)
                            l2=Label(root1,text="You should observe taking deep breaths, and visualize yourself calmn.",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                            l2.place(x=750,y=350,anchor=CENTER)
                            l3=Label(root1,text="Be mindful of your thoughts and admit that you are nervous and try to change your focus.",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                            l3.place(x=740,y=470,anchor=CENTER)
                            l4 = Label(root1, text ="Mood care tips", justify= CENTER, font=("Times", 25,"bold","underline"),bd=20,fg="salmon", bg="peach puff")
                            l4.pack(side=TOP)
                            l5= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                            l5.pack(side=BOTTOM)
                            root1.configure(bg="peach puff")
                            root1.mainloop()
                       elif  button == ("button2"):
                           root1= Toplevel()
                           root1.title("Mood care tips")
                           root1.geometry("1600x1600")
                           l1= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                           l1.place(x=300,y=100)
                           l2=Label(root1,text="A positive emotion to be felt indeed! Try to be persistent in maintaing happiness.",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                           l2.place(x=750,y=350,anchor=CENTER)
                           l3=Label(root1,text="Be grateful and think less of negativitiy, embrace your personality and think positively quite often.",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                           l3.place(x=740,y=470,anchor=CENTER)
                           l4 = Label(root1, text ="Mood care tips", justify= CENTER, font=("Times", 25,"bold","underline"),bd=20,fg="salmon", bg="peach puff")
                           l4.pack(side=TOP)
                           l5= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                           l5.pack(side=BOTTOM)
                           root1.configure(bg="peach puff")
                           root1.mainloop()
                       elif  button == ("button3"):
                           root1= Toplevel()
                           root1.title("Mood care tips")
                           root1.geometry("1600x1600")
                           l1= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                           l1.place(x=300,y=100)
                           l2=Label(root1,text="A healthy emotion to be felt but not too often.Do not despair over minute issues and do whatever makes you happy.",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                           l2.place(x=750,y=350,anchor=CENTER)
                           l3=Label(root1,text="Do not stress about what makes you sad, take proper amount of sleep.Re-call your happy times and rejuvenate!",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                           l3.place(x=740,y=470,anchor=CENTER)
                           l4 = Label(root1, text ="Mood care tips", justify= CENTER, font=("Times", 25,"bold","underline"),bd=20,fg="salmon", bg="peach puff")
                           l4.pack(side=TOP)
                           l5= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                           l5.pack(side=BOTTOM)
                           root1.configure(bg="peach puff")
                           root1.mainloop()
                       elif  button == ("button"):
                           root1= Toplevel()
                           root1.title("Mood care tips")
                           root1.geometry("1600x1600")
                           l1= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                           l1.place(x=300,y=100)
                           l2=Label(root1,text="Take a break from your work and express your feelings to others. Avoid caging your feelings and thoughts",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                           l2.place(x=750,y=350,anchor=CENTER)
                           l3=Label(root1,text="Contemplate on your decisions, relax and take gradual steps to overcome frusteration",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                           l3.place(x=740,y=470,anchor=CENTER)
                           l4 = Label(root1, text ="Mood care tips", justify= CENTER, font=("Times", 25,"bold","underline"),bd=20,fg="salmon", bg="peach puff")
                           l4.pack(side=TOP)
                           l5= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                           l5.pack(side=BOTTOM)
                           root1.configure(bg="peach puff")
                           root1.mainloop()
                       elif  button == ("button5"):
                          root1 = Toplevel()
                          root1.title("Mood care tips")
                          root1.geometry("1600x1600")
                          l1= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                          l1.place(x=300,y=100)
                          l2=Label(root1,text="Do not let things get to your head.Avoid getting into fights with others. Try to stay sensible and act maturely",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                          l2.place(x=750,y=350,anchor=CENTER)
                          l3=Label(root1,text="Do not intake unhealthy food too often. It will eventually improve your temper",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                          l3.place(x=740,y=470,anchor=CENTER)
                          l4=Label(root1,text="Take deep breaths and divert your focus when feeling angry!",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                          l4.place(x=740,y=550,anchor=CENTER)
                          l5 = Label(root1, text ="Mood care tips", justify= CENTER, font=("Times", 25,"bold","underline"),bd=20,fg="salmon", bg="peach puff")
                          l5.pack(side=TOP)
                          l6= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                          l6.pack(side=BOTTOM)
                          root1.configure(bg="peach puff")
                          root1.mainloop()
                       elif  button == ("button6"):
                          root1= Toplevel()
                          root1.title("Mood care tips")
                          root1.geometry("1600x1600")
                          l1= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                          l1.place(x=300,y=100)
                          l2=Label(root1,text="Avoid overthinking, monitor your stress levels and maintain boundaries from anxious things.",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                          l2.place(x=750,y=350,anchor=CENTER)
                          l3=Label(root1,text="Be gentle to yourself and welcome positivity. Do not pay attention to disturbing thoughts and be persistent in your process",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                          l3.place(x=740,y=470,anchor=CENTER)
                          l4 = Label(root1, text ="Mood care tips", justify= CENTER, font=("Times", 20,"bold","underline"),bd=20,fg="salmon", bg="peach puff")
                          l4.pack(side=TOP)
                          l5= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                          l5.pack(side=BOTTOM)
                          root1.configure(bg="peach puff")
                          root1.mainloop()
                       elif  button == ("button7"):
                          root1= Toplevel()
                          root1.title("Mood care tips")
                          root1.geometry("1600x1600")
                          l1= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                          l1.place(x=300,y=100)
                          l2=Label(root1,text="Take things slowly.Be comfortable in taking gradual steps towards your goals. Maintain a healthy and productive routine",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                          l2.place(x=750,y=350,anchor=CENTER)
                          l3=Label(root1,text="Be confident in your personality and take your tasks seriously.",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                          l3.place(x=740,y=470,anchor=CENTER)
                          l4 = Label(root1, text ="Mood care tips", justify= CENTER, font=("Times", 25,"bold","underline"),bd=20,fg="salmon", bg="peach puff")
                          l4.pack(side=TOP)
                          l5= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                          l5.pack(side=BOTTOM)
                          root1.configure(bg="peach puff")
                          root1.mainloop()
                       elif  button == ("button8"):
                          root1= Toplevel()
                          root1.title("Mood care tips")
                          root1.geometry("1600x1600")
                          l1= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                          l1.place(x=300,y=100)
                          l2=Label(root1,text="Good to maintain enthusiasism! Make sure to balance life as well, stay away from work obsession.",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                          l2.place(x=750,y=350,anchor=CENTER)
                          l3=Label(root1,text="Be confident over your personality and take small breaks in between to preserve your energy!",font=("Times",20),bd=20, fg="salmon",bg="bisque")
                          l3.place(x=740,y=470,anchor=CENTER)
                          l4 = Label(root1, text ="Mood care tips", justify= CENTER, font=("Times", 25,"bold","underline"),bd=20,fg="salmon", bg="peach puff")
                          l4.pack(side=TOP)
                          l5= Label(root1,text="********************************************************************",font=("Times",20),bd=20,fg="salmon",bg="bisque")
                          l5.pack(side=BOTTOM)
                          root1.configure(bg="peach puff")
                          root1.mainloop()   
                   #BUTTON FUNCTIONALITIES FOR IMAGES
                   def b1():
                        button1["command"]=mood_tip_suggest1("button1")
                   def b2():
                       button2["command"]=mood_tip_suggest1("button2")
                   def b3():
                       button3["command"]=mood_tip_suggest1("button3")
                   def b4():
                       button["command"]=mood_tip_suggest1("button")    
                   def b5():
                       button5["command"]=mood_tip_suggest1("button5")
                   def b6():
                       button6["command"]=mood_tip_suggest1("button6")
                   def b7():
                       button7["command"]=mood_tip_suggest1("button7")
                   def b8():
                       button8["command"]=mood_tip_suggest1("button8")
                   #ADDING IMAGES AND BUTTONS IN MAIN WINDOW
                   # image = Image.open("nervous.jpg")
                   # photo = ImageTk.PhotoImage(image)
                   # my_label1 = Label(image = photo,height = 150, width = 225)
                   # my_label1.image=photo
                   # my_label1.place(x=100,y=200)
                   button1 = Button(root1,text="Nervous", width=20,bg="red",fg='white',font=('arial',12, "italic", "bold"), bd=14)
                   button1.place(x=200,y=300)
                   button1["command"]=b1
                       
                   # my_image2 = ImageTk.PhotoImage(Image.open("happy.jpg"))
                   # my_label2= Label(image = my_image2, height= 150,width = 225 )
                   # my_label2.place(x=450,y=200)
                   button2 = Button(root1,text="Happy", width=20,bg="red",fg='white',font=('arial',12, "italic", "bold"), bd=14)
                   button2["command"]=b2
                   button2.place(x=550,y=300)
                   # my_image3 = ImageTk.PhotoImage(Image.open("sad.jpg"))
                   # my_label3= Label(image = my_image3, height= 150,width = 225 )
                   # my_label3.place(x=800,y=200)
                   button3 = Button(root1,text="Sad", width=20,bg="red",fg='white',font=('arial',12, "italic", "bold"), bd=14)
                   button3.place(x=900,y=300)
                   button3["command"]=b3
                   # my_image4= ImageTk.PhotoImage(Image.open("frusterated.jpg"))
                   # my_label4= Label(image = my_image4, height= 150,width = 225 )
                   # my_label4.place(x=1150,y=200)
                   button = Button(root1,text="Frusterated", width=20,bg="red",fg='white',font=('arial',12, "italic", "bold"), bd=14)
                   button.place(x=1220,y=300)
                   button["command"]=b4
                   # my_image5= ImageTk.PhotoImage(Image.open("angry.jpg"))
                   # my_label5= Label(image = my_image5, height= 150,width = 225 )
                   # my_label5.place(x=100,y=450)
                   button5 = Button(root1,text="Angry", width=20,bg="red",fg='white',font=('arial',12, "italic", "bold"), bd=14)
                   button5.place(x=200,y=500)
                   button5["command"]=b5
                   # my_image6= ImageTk.PhotoImage(Image.open("anxious.jpg"))
                   # my_label6= Label(image = my_image6, height= 150,width = 225 )
                   # my_label6.place(x=450,y=450)
                   button6 = Button(root1,text="Anxious", width=20,bg="red",fg='white',font=('arial',12, "italic", "bold"), bd=14)
                   button6.place(x=550,y=500)
                   button6["command"]=b6
                   # my_image7= ImageTk.PhotoImage(Image.open("demotivated.jpg"))
                   # my_label7= Label(image = my_image7, height= 150,width = 225 )
                   # my_label7.place(x=800,y=450)
                   button7 = Button(root1,text="Demotivated", width=20,bg="red",fg='white',font=('arial',12, "italic", "bold"), bd=14)
                   button7.place(x=880,y=500)
                   button7['command']=b7
                   # my_image8= ImageTk.PhotoImage(Image.open("enthusiastic.png"))
                   # my_label8= Label(image = my_image8, height= 150,width = 225 )
                   # my_label8.place(x=1150,y=450)
                   button8 = Button(root1,text="Enthusiastic", width=20,bg="red",fg='white',font=('arial',12, "italic", "bold"), bd=14)
                   button8.place(x=1220,y=500)
                   button8["command"]=b8
                   #TITLE OF WINDOW "MOOD TRACKER"
                   l = Label(root1, text ="MOOD TRACKER", justify= CENTER, font=("Arial", 30,"italic","bold","underline"),bd=20, fg="black",bg="pink")
                   l2 = Label(root1, text ="How are you feeling today?", justify= CENTER, font=("Arial", 20,"italic","bold","underline"),bd=20,fg="black", bg="pink")
                   l.place(x=800, y=50, anchor=CENTER)
                   l2.place(x=800, y=150, anchor=CENTER)
                   #EXIT BUTTON
                   button_quit = Button(root1,text="Exit", justify = CENTER, width=20, height=2,bg="red",fg='black',font=('arial',18, "italic", "bold"), bd=14)
                   button_quit.place(x=600,y=650)
                   button_quit['command']=root1.destroy
                   root1.mainloop()


